# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: messages.proto
# Protobuf Python Version: 6.32.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    1,
    '',
    'messages.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\"\x1d\n\tStoreData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"\x1b\n\x07GetData\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"0\n\x17\x46ragment_Status_Request\x12\x15\n\rfragment_name\x18\x01 \x01(\t\"V\n\x18\x46ragment_Status_Response\x12\x15\n\rfragment_name\x18\x01 \x01(\t\x12\x12\n\nis_present\x18\x02 \x01(\x08\x12\x0f\n\x07node_id\x18\x03 \x01(\t\"-\n\x06header\x12#\n\x0crequest_type\x18\x01 \x01(\x0e\x32\r.request_type*[\n\x0crequest_type\x12\x17\n\x13\x46RAGMENT_STATUS_REQ\x10\x00\x12\x15\n\x11\x46RAGMENT_DATA_REQ\x10\x01\x12\x1b\n\x17STORE_FRAGMENT_DATA_REQ\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUEST_TYPE']._serialized_start=263
  _globals['_REQUEST_TYPE']._serialized_end=354
  _globals['_STOREDATA']._serialized_start=18
  _globals['_STOREDATA']._serialized_end=47
  _globals['_GETDATA']._serialized_start=49
  _globals['_GETDATA']._serialized_end=76
  _globals['_FRAGMENT_STATUS_REQUEST']._serialized_start=78
  _globals['_FRAGMENT_STATUS_REQUEST']._serialized_end=126
  _globals['_FRAGMENT_STATUS_RESPONSE']._serialized_start=128
  _globals['_FRAGMENT_STATUS_RESPONSE']._serialized_end=214
  _globals['_HEADER']._serialized_start=216
  _globals['_HEADER']._serialized_end=261
# @@protoc_insertion_point(module_scope)
